- README.md
- default.json
Motivation
---
`prCreation: pending` will never create a PR if a new renovate branch is failing tests, because the PR checks are still "pending", which means we'll probably never see the failing tests and never attempt to fix them
Modification
---
Let Pending PRs be created, hopefully that doesn't break stabilityDays
https://centeredge.atlassian.net/browse/PHNX-9093
> Let Pending PRs be created (PHNX-9093)

- default.json
Motivation
---
The preset `config:base` automatically ignores package manager files from **tests** files, we don't want to ignore packages in tests. Let's not ignore anything and then selectively ignore paths when needed
Modification
---
Don't ignore any paths
https://centeredge.atlassian.net/browse/PHNX-9098
> Don't ignore any paths (PHNX-9098)

- phoenix/nuget-minor.json
Motivation
---
Linq2Couchbase 1.4.2 has breaking changes that will cause problems if not handled carefully 
Modification
---
Ignore automatic updates to Linq2Couchbase on versions greater than than 1.4.2
https://centeredge.atlassian.net/browse/PHNX-9282
> Ignore Linq2Couchbase >= 1.4.2 (PHNX-9282)

- README.md
- phoenix/default.json
Motivation
----------
There are a few fixes and notes to add I don't want to create multiple subtasks for
Modifications
-------------
- Renovate builds are failing probably because there are '(' in the branch name, use branchNameStrict to fix that
- Run renovate just once a week instead of every hour to have less noise
- Add some text in the pr body to easier find CE specific instructions
https://centeredge.atlassian.net/browse/PHNX-9356
> Apply various Renovate tweaks (PHNX-9356)

- README.md
- phoenix/private-packages.json
Motivation
----------
We would like to be able to use Renovate to help mass update our private packages across all repos
Modifications
-------------
- Add configuration to allow updating private packages
- Add more notes on random things
https://centeredge.atlassian.net/browse/PHNX-9425
> Add configuration to allow updating private packages (PHNX-9425)

- phoenix/private-packages.json
Motivation
------------
Upgrading CenterEdge.Metrics.AspNetCore to 2.3.0 is causing build problems in several repositories and there doesn't seem to be an easy fix, so let's not automatically update it to keep other packages updates moving through successfully
```
Application startup exception: System.InvalidOperationException: Unable to resolve service for type 'CenterEdge.Metrics.ISpanMetricSink' while attempting to activate 'CenterEdge.Metrics.AspNetCore.CenterEdgeMetricMiddleware'.
```
Modifications
------------
Don't automatically upgrade CenterEdge.Metrics.AspNetCore to 2.3.0
https://centeredge.atlassian.net/browse/PHNX-9532
> Don't upgrade CenterEdge.Metrics.AspNetCore to 2.3.0 (PHNX-9532)

- phoenix/npm-minor.json
- phoenix/nuget-minor.json
Motivation
------------
Including our own private packages in the mass of bulk update PRs is asking for things to unexpectedly break and we should probably be more considerate of auto merging our own packages in the mix with other unrelated stuff
Modifications
------------
- Exclude our private packages in the grouped PRs, instead Renovate will create an individual PR for each private package
- Increase the days for the stability days check because that makes me feel better
https://centeredge.atlassian.net/browse/PHNX-952
> Don't include private packages in the grouped PRs (PHNX-952)

- phoenix/nuget-minor.json
Motivation
---
OpenTelemetry packages with version 1.0.0-rc9.10 is causing problems try just waiting for the next packages releases to update this
Modification
---
Ignore OpenTelemetry.xxx 1.0.0-rc9.10
https://centeredge.atlassian.net/browse/PHNX-9821
> Ignore OpenTelemetry.xxx 1.0.0-rc9.10 (PHNX-9821)

- phoenix/private-packages.json
Motivation
---
We want to let renovate handle creating all the prs to update Phoenix.Microservice.Advantage everywhere
Modification
---
- Add Phoenix.Microservice.Advantage to private package list
- Change the renovate schedule to run at any time only for our private packages because we don't want to wait around for a week for renovate to see updates
https://centeredge.atlassian.net/browse/PHNX-9865
> Add Phoenix.Microservice.Advantage to private package list (PHNX-9865)

- phoenix/nuget-minor.json
Motivation
--------------
OpenTelemetry packages newer than 1.0.0-rc9.9 can cause deployments to fail.
Modifications
--------------
Set max allowed version to 1.0.0-rc9.9.
https://centeredge.atlassian.net/browse/PHNX-10007
> Set Max OpenTelemetry Version (PHNX-10007)

- phoenix/nuget-minor.json
Motivation
---
NEST versions greater than 7.8.1 are causing errors in waivers service smoke tests "The client noticed that the server is not a supported distribution of Elasticsearch"
Modification
---
Ignore NEST versions greater than 7.8.1
https://centeredge.atlassian.net/browse/PHNX-10087
> Ignore NEST versions greater than 7.8.1 (PHNX-10087)

- phoenix/default.json
Motivation
---
We want to ignore artifactErrors because renovate was complaining about not being able to find some of our private package, and so blocking merges. However, we already knew that a lot of our packages renovate won't be able to find because we have to manually add each one to a white list. And we couldn't find any other readily available documentation on what other kind of artifact errors it could find
Modifications
---
Ignore artifactErrors
Results
---
Stop blocking merges
https://centeredge.atlassian.net/browse/PHNX-10197
> Ignore artifactErrors (PHNX-10197)

- phoenix/nuget-minor.json
Motivation
---
Experienced a build fail for Open Telemetry package (Exporter.Jaeger" Version="1.4.0" />
Modification
---
Ignore this package for future updates
https://centeredge.atlassian.net/browse/PHNX-10265
> Ignore OT.Exporter.Jaeger>1.3.2 (PHNX-10265)

- phoenix/nuget-minor.json
Motivation 
---
Multiple PR's up for swashbuckle 6.5.0 update and they all fail to build
`Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'Swashbuckle.AspNetCore.Swagger, Version=6.5.0.0, Culture=neutral, PublicKeyToken=62657d7474907593'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'Swashbuckle.AspNetCore.Swagger, Version=6.5.0.0, Culture=neutral, PublicKeyToken=62657d7474907593'`
Modification
---
Ignore this update 
https://centeredge.atlassian.net/browse/PHNX-10367
> Ignore Swashbuckle CLI past 6.4.0(PHNX-10367)

- phoenix/private-packages.json
Motivation
---
CECloud.Messenger has an update to stop logging "Requesting messages from queue..." all the time
Modifications
---
Add CECloud.Messenger to private packages whitelist
https://centeredge.atlassian.net/browse/PHNX-10383
> Add CECloud.Messenger to private packages whitelist (PHNX-10383)

- phoenix/npm-minor.json
Motivation
---
When @types/lodash was upgraded to 4.14.194 errors in our CI tests started showing similar to this:
```
node_modules/@types/lodash/common/object.d.ts(1025,21): error TS1110: Type expected.
node_modules/@types/lodash/common/object.d.ts(1026,24): error TS1005: ':' expected.
node_modules/@types/lodash/common/object.d.ts(1026,38): error TS1005: ';' expected.
node_modules/@types/lodash/common/object.d.ts(1027,26): error TS1005: ':' expected.
```
Modification
---
Only allow @types/lodash less than 4.14.194
https://centeredge.atlassian.net/browse/PHNX-12420
> Only allow @types/lodash less than 4.14.194 (PHNX-12420)

- phoenix/default.json
Motivation
---
Github and renovate are fighting over the PR title and doing this:
example https://github.com/CenterEdge/CECloud.Webstores/pull/3530
But why does renovate keep updating stuff? I thought we made it only run on Monday
Modification
---
Try using an exact schedule example included in the Renovate docs https://docs.renovatebot.com/presets-schedule/
https://centeredge.atlassian.net/browse/PHNX-12686
> Update the renovate schedule (PHNX-12686)

- phoenix/nuget-minor.json
Motivation
---
We have had deployment issues with this package that sneaks by automated testing, we want to avoid this by excluding it from renovate PRS 
Modification
---
- Exclude package from new PRS made by renovate 
https://centeredge.atlassian.net/browse/PHNX-13147
> Exclude OpenTelemetry.OTProtocol Versions Newer than 1.3.2  (PHNX-13147)

- phoenix/default.json
- phoenix/github-actions.json
Now that we're starting to use GitHub actions pretty heavily, we want package update prs to include anything for github-actions, including our own CenterEdge github actions
- Remove github-actions from the ignore list
https://centeredge.atlassian.net/browse/PHNX-13224
> Enable github-actions (PHNX-13224)

- phoenix/default.json
- phoenix/github-actions.json
GitHub actions renovate updates
- Adjust the group name, 'Updates' is already added to the group name as a prefix in PR's, no reason to have it in the group name
- Reference the github-actions.json in the default config
https://centeredge.atlassian.net/browse/PHNX-13231
> Extend github-actions.json (PHNX-13231)

- phoenix/github-actions.json
Reducing the number of PR's we have to merge
- Override the default `separateMajorMinor` and `separateMinorPatch` values from true to false
- Add a group slug
https://centeredge.atlassian.net/browse/PHNX-13366
> Group all GHA updates into one PR (PHNX-13366)
